### ISSUE TITLE
Remove "Section" from saved configuration

### ISSUE THREAD

**Issue by torbacz** [CShark-Hub/Mako-IoT.Home#62]
When we save configuration into device, we are saving all properties including the const SectionName. We should remove that, because it takes only place in memory.

We can:
- Add "JsonIgnore" attribute to consts (not preferred, as it would introduce dependency on Json lib)
- Move SectionName to other class - simplest 
- Extend nanoframework with ability to disable serializing consts fields

**Comment by CoryCharlton** [comment]
I'm about to open an issue on the `nanoFramework.Json` library regarding this. I don't think it should be serializing static fields/properties at all.

**Comment by CoryCharlton** [comment]
This should be resolved now: https://github.com/CShark-Hub/Mako-IoT.Device.Services.Configuration/commit/ca5e5f0c6750200d68ad7289948f32314053ec1a

**Comment by torbacz** [comment]
Yes, new version is already pushed. Closing. Thanks.
